[2024-07-07T14:06:57.405+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-07T14:06:57.455+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: clickhouse_etl_dag.extract manual__2024-07-07T14:06:49.652767+00:00 [queued]>
[2024-07-07T14:06:57.468+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: clickhouse_etl_dag.extract manual__2024-07-07T14:06:49.652767+00:00 [queued]>
[2024-07-07T14:06:57.470+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 0
[2024-07-07T14:06:57.502+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): extract> on 2024-07-07 14:06:49.652767+00:00
[2024-07-07T14:06:57.511+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=101) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-07T14:06:57.514+0000] {standard_task_runner.py:63} INFO - Started process 110 to run task
[2024-07-07T14:06:57.513+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'clickhouse_etl_dag', 'extract', 'manual__2024-07-07T14:06:49.652767+00:00', '--job-id', '25', '--raw', '--subdir', 'DAGS_FOLDER/clickhouse.py', '--cfg-path', '/tmp/tmpujum6xq8']
[2024-07-07T14:06:57.516+0000] {standard_task_runner.py:91} INFO - Job 25: Subtask extract
[2024-07-07T14:06:57.601+0000] {task_command.py:426} INFO - Running <TaskInstance: clickhouse_etl_dag.extract manual__2024-07-07T14:06:49.652767+00:00 [running]> on host dfb367ef2d3b
[2024-07-07T14:06:57.790+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='franklinnwosu008@gmail.com' AIRFLOW_CTX_DAG_OWNER='Ifeanyi_DArTech_Org' AIRFLOW_CTX_DAG_ID='clickhouse_etl_dag' AIRFLOW_CTX_TASK_ID='extract' AIRFLOW_CTX_EXECUTION_DATE='2024-07-07T14:06:49.652767+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-07T14:06:49.652767+00:00'
[2024-07-07T14:06:57.805+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-07T14:06:58.108+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-07T14:06:58.112+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/modules/extract.py", line 49, in fetch_data
    df.to_csv('./dags/raw_files/tripdata.csv', index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
    return DataFrameRenderer(formatter).to_csv(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
    with get_handle(
         ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: 'dags/raw_files'
[2024-07-07T14:06:58.140+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=clickhouse_etl_dag, task_id=extract, run_id=manual__2024-07-07T14:06:49.652767+00:00, execution_date=20240707T140649, start_date=20240707T140657, end_date=20240707T140658
[2024-07-07T14:06:58.174+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 25 for task extract (Cannot save file into a non-existent directory: 'dags/raw_files'; 110)
[2024-07-07T14:06:58.214+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-07T14:06:58.234+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
